#!/usr/bin/env bun

/**
 * Cinematic Video Storyboard Generator
 * Creates structured storyboards for narrative video production
 */

import { parseArgs } from "node:util";

const args = parseArgs({
  allowPositionals: true,
  options: {
    title: { type: "string", short: "t" },
    genre: { type: "string", short: "g" },
    duration: { type: "string", short: "d" },
    characters: { type: "string", short: "c" },
    output: { type: "string", short: "o", default: "storyboard.md" },
    help: { type: "boolean", short: "h" },
  },
});

if (args.values.help) {
  console.log(`
Cinematic Video Storyboard Generator

Usage:
  bun storyboard.ts [options]

Options:
  -t, --title       Story/film title
  -g, --genre       Genre (drama, thriller, romance, action, horror)
  -d, --duration    Total runtime (e.g., "2 minutes", "90 seconds")
  -c, --characters  Character descriptions (comma-separated)
  -o, --output      Output filename (default: storyboard.md)
  -h, --help        Show this help

Examples:
  bun storyboard.ts -t "The Last Letter" -g drama -d "90 seconds" -c "Maya:30s dark hair cream sweater"
`);
  process.exit(0);
}

const { title, genre, duration, characters, output } = args.values;

interface Scene {
  number: number;
  name: string;
  duration: string;
  beats: Beat[];
}

interface Beat {
  shot: string;
  description: string;
  duration: string;
  notes?: string;
}

interface Character {
  name: string;
  age?: string;
  appearance: string;
  keyTraits: string[];
}

function parseCharacters(input?: string): Character[] {
  if (!input) return [];
  
  return input.split(",").map((c, i) => {
    const parts = c.trim().split(":");
    const name = parts[0]?.trim() || `Character ${i + 1}`;
    const details = parts[1]?.trim() || "";
    
    return {
      name,
      appearance: details,
      keyTraits: [],
    };
  });
}

function generateStoryboard(): string {
  const chars = parseCharacters(characters);
  const runtime = duration || "2 minutes";
  const filmTitle = title || "Untitled Story";
  const filmGenre = genre || "drama";
  
  // Generate structure based on genre
  const template = getGenreTemplate(filmGenre);
  
  let md = `# ${filmTitle}

## Overview
- **Genre:** ${filmGenre}
- **Duration:** ${runtime}
- **Characters:** ${chars.map((c) => c.name).join(", ") || "TBD"}

---

## Characters

`;
  
  if (chars.length > 0) {
    chars.forEach((c) => {
      md += `### ${c.name}
${c.appearance || "Description TBD"}

**Key Traits:**
- 
- 

---

`;
    });
  } else {
    md += `### Character 1
*Add character description*

**Key Traits:**
- Physical markers
- Signature clothing
- Characteristic posture

---

`;
  }

  md += `## Act Structure

### ACT 1 - Setup
*Establish world, characters, and inciting incident*

---

`;
  
  template.act1.forEach((scene) => {
    md += formatScene(scene);
  });

  md += `### ACT 2 - Confrontation
*Rising action, complications, and character development*

---

`;
  
  template.act2.forEach((scene) => {
    md += formatScene(scene);
  });

  md += `### ACT 3 - Resolution
*Climax and resolution*

---

`;
  
  template.act3.forEach((scene) => {
    md += formatScene(scene);
  });

  md += `## Production Notes

### Shot List Summary
| Shot Type | Count | Purpose |
|-----------|-------|---------|
| Wide | | Establishing |
| Medium | | Dialogue/Interaction |
| Close-up | | Emotion |
| Extreme Close-up | | Details |

### Audio Design
- [ ] Ambient sound for each location
- [ ] Music cues for emotional beats
- [ ] Sound effects for actions
- [ ] Silence moments noted

### Visual Continuity Checklist
- [ ] Character appearance consistent
- [ ] Lighting matches within scenes
- [ ] Props tracked
- [ ] Screen direction maintained

---

## Prompt Reference

### Establishing Shot Template
\`\`\`
"[INTERIOR/EXTERIOR] [LOCATION], [TIME OF DAY], [LIGHTING DESCRIPTION],
[KEY ACTION], [ATMOSPHERE/MOOD], cinematic 4K"
\`\`\`

### Character Shot Template
\`\`\`
"[SHOT TYPE], [CHARACTER NAME] ([AGE], [DISTINGUISHING FEATURES]),
[ACTION/EXPRESSION], [ENVIRONMENT], [LIGHTING], [MOOD]"
\`\`\`

---

*Generated by cinematic-video skill*
`;
  
  return md;
}

function formatScene(scene: Scene): string {
  let md = `#### Scene ${scene.number}: ${scene.name}
**Duration:** ${scene.duration}

| Shot | Description | Duration | Notes |
|------|-------------|----------|-------|
`;
  
  scene.beats.forEach((beat) => {
    const notes = beat.notes ? ` *${beat.notes}*` : "";
    md += `| ${beat.shot} | ${beat.description} | ${beat.duration} |${notes} |\n`;
  });
  
  md += "\n---\n\n";
  return md;
}

interface GenreTemplate {
  act1: Scene[];
  act2: Scene[];
  act3: Scene[];
}

function getGenreTemplate(genre: string): GenreTemplate {
  const templates: Record<string, GenreTemplate> = {
    drama: {
      act1: [
        {
          number: 1,
          name: "Opening",
          duration: "15-20 sec",
          beats: [
            { shot: "Wide", description: "Establish location and atmosphere", duration: "4 sec" },
            { shot: "Medium", description: "Introduce protagonist in status quo", duration: "3 sec" },
            { shot: "Close-up", description: "Revealing character detail or emotion", duration: "3 sec" },
          ],
        },
        {
          number: 2,
          name: "Inciting Incident",
          duration: "10-15 sec",
          beats: [
            { shot: "Medium", description: "Event that disrupts equilibrium", duration: "4 sec" },
            { shot: "Close-up", description: "Protagonist's reaction", duration: "3 sec" },
            { shot: "Wide", description: "New situation established", duration: "3 sec" },
          ],
        },
      ],
      act2: [
        {
          number: 3,
          name: "Rising Action",
          duration: "20-30 sec",
          beats: [
            { shot: "Medium", description: "Character faces challenge", duration: "4 sec" },
            { shot: "Close-up", description: "Emotional response", duration: "3 sec" },
            { shot: "Medium", description: "Attempt to resolve", duration: "4 sec" },
            { shot: "Close-up", description: "Complication or setback", duration: "3 sec" },
          ],
        },
        {
          number: 4,
          name: "Midpoint",
          duration: "15-20 sec",
          beats: [
            { shot: "Wide", description: "Stakes raised visually", duration: "4 sec" },
            { shot: "Close-up", description: "Internal shift or revelation", duration: "4 sec" },
            { shot: "Medium", description: "New determination", duration: "3 sec" },
          ],
        },
      ],
      act3: [
        {
          number: 5,
          name: "Climax",
          duration: "15-20 sec",
          beats: [
            { shot: "Medium", description: "Final confrontation or decision", duration: "5 sec" },
            { shot: "Close-up", description: "Emotional peak", duration: "4 sec" },
            { shot: "Wide", description: "Resolution visualised", duration: "4 sec" },
          ],
        },
        {
          number: 6,
          name: "Resolution",
          duration: "10-15 sec",
          beats: [
            { shot: "Medium", description: "New equilibrium", duration: "4 sec" },
            { shot: "Close-up", description: "Thematic final image", duration: "3 sec" },
            { shot: "Wide", description: "Fade out with meaning", duration: "4 sec", notes: "Fade" },
          ],
        },
      ],
    },
    thriller: {
      act1: [
        {
          number: 1,
          name: "Opening Mystery",
          duration: "15-20 sec",
          beats: [
            { shot: "Wide", description: "Atmospheric establishing shot", duration: "4 sec", notes: "Low key lighting" },
            { shot: "Close-up", description: "Telling detail or clue", duration: "2 sec" },
            { shot: "Medium", description: "Protagonist introduction", duration: "3 sec" },
          ],
        },
      ],
      act2: [
        {
          number: 2,
          name: "Tension Building",
          duration: "30-40 sec",
          beats: [
            { shot: "Medium", description: "Investigation or discovery", duration: "4 sec", notes: "Handheld" },
            { shot: "Close-up", description: "Something's wrong...", duration: "2 sec", notes: "Dutch angle" },
            { shot: "Wide", description: "Threat revealed or implied", duration: "3 sec" },
          ],
        },
      ],
      act3: [
        {
          number: 3,
          name: "Confrontation",
          duration: "20-25 sec",
          beats: [
            { shot: "Close-up", description: "Peak tension", duration: "2 sec" },
            { shot: "Wide", description: "Resolution of threat", duration: "4 sec" },
            { shot: "Medium", description: "Aftermath", duration: "3 sec", notes: "Silence" },
          ],
        },
      ],
    },
    romance: {
      act1: [
        {
          number: 1,
          name: "Meeting",
          duration: "20 sec",
          beats: [
            { shot: "Wide", description: "Setting the mood", duration: "4 sec", notes: "Warm lighting" },
            { shot: "Medium", description: "First glimpse of love interest", duration: "3 sec" },
            { shot: "Close-up", description: "Connection moment", duration: "3 sec" },
          ],
        },
      ],
      act2: [
        {
          number: 2,
          name: "Growing Closer",
          duration: "30 sec",
          beats: [
            { shot: "Two-shot", description: "Chemistry building", duration: "4 sec", notes: "Soft focus" },
            { shot: "Close-up", description: "Vulnerability shared", duration: "4 sec" },
            { shot: "Medium", description: "Intimacy or connection", duration: "4 sec" },
          ],
        },
      ],
      act3: [
        {
          number: 3,
          name: "Declaration",
          duration: "20 sec",
          beats: [
            { shot: "Close-up", description: "Emotional declaration", duration: "4 sec" },
            { shot: "Two-shot", description: "Union", duration: "5 sec" },
            { shot: "Wide", description: "Happily ever after feeling", duration: "4 sec", notes: "Golden hour" },
          ],
        },
      ],
    },
    action: {
      act1: [
        {
          number: 1,
          name: "High Stakes Open",
          duration: "15 sec",
          beats: [
            { shot: "Wide", description: "Explosive opening", duration: "3 sec", notes: "Dynamic" },
            { shot: "Medium", description: "Hero in action", duration: "2 sec" },
            { shot: "Close-up", description: "Determination", duration: "2 sec" },
          ],
        },
      ],
      act2: [
        {
          number: 2,
          name: "Confrontations",
          duration: "40 sec",
          beats: [
            { shot: "Wide", description: "Action sequence", duration: "3 sec", notes: "Multiple cuts" },
            { shot: "Close-up", description: "Impact moments", duration: "1 sec" },
            { shot: "Medium", description: "Chase or fight continuation", duration: "3 sec" },
          ],
        },
      ],
      act3: [
        {
          number: 3,
          name: "Final Showdown",
          duration: "25 sec",
          beats: [
            { shot: "Wide", description: "Ultimate challenge", duration: "4 sec" },
            { shot: "Close-up", description: "Victory moment", duration: "2 sec" },
            { shot: "Medium", description: "Heroic conclusion", duration: "4 sec" },
          ],
        },
      ],
    },
    horror: {
      act1: [
        {
          number: 1,
          name: "Dread Establishment",
          duration: "20 sec",
          beats: [
            { shot: "Wide", description: "Isolated location", duration: "5 sec", notes: "Long take" },
            { shot: "Medium", description: "Character unaware", duration: "4 sec" },
            { shot: "Close-up", description: "Something watching", duration: "2 sec", notes: "POV" },
          ],
        },
      ],
      act2: [
        {
          number: 2,
          name: "Escalation",
          duration: "35 sec",
          beats: [
            { shot: "Long take", description: "Building dread", duration: "8 sec", notes: "No cuts" },
            { shot: "Close-up", description: "First scare", duration: "2 sec" },
            { shot: "Wide", description: "Fleeing or hiding", duration: "4 sec", notes: "Darkness" },
          ],
        },
      ],
      act3: [
        {
          number: 3,
          name: "Confronting Evil",
          duration: "20 sec",
          beats: [
            { shot: "Close-up", description: "Face the horror", duration: "3 sec" },
            { shot: "Wide", description: "Escape or end", duration: "5 sec" },
            { shot: "Ambiguous", description: "Lingering threat?", duration: "3 sec", notes: "Silence" },
          ],
        },
      ],
    },
  };
  
  return templates[genre.toLowerCase()] || templates.drama;
}

// Main execution
const storyboard = generateStoryboard();

if (output) {
  const path = `/home/workspace/${output}`;
  Bun.write(path, storyboard);
  console.log(`Storyboard saved to: ${path}`);
} else {
  console.log(storyboard);
}
