#!/usr/bin/env bun
import { parseArgs } from "node:util";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const WORKSPACE = "/home/workspace";

const args = parseArgs({
  options: {
    project: { type: "string", short: "p" },
    requirements: { type: "string", short: "r" },
    output: { type: "string", short: "o" },
  },
  strict: false,
});

const project = args.values.project || "untitled-project";
const requirements = args.values.requirements || "";
const outputDir = args.values.output || join(WORKSPACE, project, "docs");

// Ensure output directory exists
mkdirSync(outputDir, { recursive: true });

// Parse requirements
const reqLines = requirements.split("\n").filter((l) => l.trim());
const features: string[] = [];
const techStack: string[] = [];
const integrations: string[] = [];

for (const line of reqLines) {
  if (line.includes("Next.js") || line.includes("Tailwind") || line.includes("shadcn")) {
    techStack.push(line);
  } else if (line.includes("integrate") || line.includes("API")) {
    integrations.push(line);
  } else if (line.trim().startsWith("-")) {
    features.push(line.replace(/^-\s*/, ""));
  }
}

const prd = `# Product Requirements Document: ${project}

## Executive Summary
${project} is a software application designed to solve specific user needs through modern web technologies.

## Problem Statement
Users need a reliable, intuitive platform that addresses their core workflow challenges.

## Goals & Success Metrics

### Primary Goals
- Deliver a seamless user experience
- Ensure secure authentication and data handling
- Provide scalable, maintainable architecture

### Success Metrics
- User adoption rate
- Task completion time
- Error rate < 1%
- Page load time < 2s

## User Stories

### Authentication
- As a user, I want to sign up with my email so I can create an account
- As a user, I want to sign up with Google so I can authenticate quickly
- As a user, I want to log out securely

### Dashboard
- As a user, I want to see a sidebar navigation so I can access different sections
- As a user, I want a responsive dashboard that works on mobile and desktop

### Integrations
- As a user, I want the app to integrate with external APIs for extended functionality

## Technical Requirements

### Frontend
${techStack.map((t) => `- ${t}`).join("\n") || "- Next.js 14+\n- TailwindCSS\n- shadcn/ui components"}

### Backend
- API routes via Next.js
- Authentication via NextAuth.js / Auth.js
- Database: PostgreSQL or SQLite

### Security
- Secure password hashing
- OAuth 2.0 for social login
- CSRF protection
- Rate limiting

## Features

${features.map((f) => `### ${f}`).join("\n\n") || "### Core Features\n- User authentication\n- Dashboard\n- API integration"}

## Integrations

${integrations.map((i) => `- ${i}`).join("\n") || "- External API integration (details TBD)"}

## UI/UX Specifications

### Layout
- Responsive sidebar navigation
- Main content area with consistent padding
- Mobile: Collapsible sidebar (hamburger menu)
- Desktop: Persistent sidebar

### Design System
- Use shadcn/ui components
- Consistent color palette
- Dark/light mode support

## API Requirements

### Authentication Endpoints
- POST /api/auth/signup - Email registration
- GET /api/auth/google - Google OAuth redirect
- GET /api/auth/callback/google - OAuth callback
- POST /api/auth/signout - Logout

### Data Endpoints
- GET /api/user - Get current user
- PUT /api/user - Update user profile

## Data Models

### User
\`\`\`typescript
interface User {
  id: string;
  email: string;
  name?: string;
  image?: string;
  authProvider: 'email' | 'google';
  createdAt: Date;
  updatedAt: Date;
}
\`\`\`

## Task Breakdown

See [TASKS.md](./TASKS.md) for detailed task list.

## Timeline Estimates

| Phase | Duration | Tasks |
|-------|----------|-------|
| Setup | 1-2 days | Project initialization, dependencies |
| Auth | 2-3 days | Email/Google authentication |
| Dashboard | 2-3 days | Layout, sidebar, responsive design |
| Integration | 2-4 days | API integration |
| Testing | 1-2 days | Unit tests, E2E tests |
| Polish | 1-2 days | UX improvements, bug fixes |

**Total Estimated Time: 9-16 days**

## Risk Assessment

| Risk | Impact | Mitigation |
|------|--------|------------|
| API documentation incomplete | High | Clarify requirements early |
| OAuth complexity | Medium | Use battle-tested libraries |
| Scope creep | Medium | Strict PRD adherence |

## Open Questions
- What specific API(s) need integration?
- What are the specific dashboard sections?
- Are there specific design requirements?
- What is the expected user volume?

---
*Generated by prd-creator skill on ${new Date().toISOString().split("T")[0]}*
`;

const outputPath = join(outputDir, "PRD.md");
writeFileSync(outputPath, prd);
console.log(`PRD created: ${outputPath}`);
