#!/usr/bin/env bun
/**
 * Boober Strengthener - Autonomous Vault Integration
 * 
 * Strategically calls vault-commands to strengthen Boober taxi safety app.
 * Designed for autonomous operation by agents and scheduled tasks.
 * 
 * Integrates with existing vault.ts and agent.ts from vault-commands skill.
 */

import { $ } from "bun";
import { writeFileSync, mkdirSync, existsSync, appendFileSync, readFileSync } from "fs";
import { join, dirname } from "path";

const WORKSPACE = "/home/workspace";
const VAULT_DIR = join(WORKSPACE, "Skills/vault-commands/scripts");
const BOOBER_DIR = join(WORKSPACE, "Boober");
const REPORTS_DIR = join(BOOBER_DIR, "agent-reports");
const AGENTS_MD = join(WORKSPACE, "AGENTS.md");
const BOOBER_AGENTS_MD = join(BOOBER_DIR, "AGENTS.md");
const INSIGHTS_FILE = join(BOOBER_DIR, "INSIGHTS.md");
const LAUNCH_CHECKLIST = join(BOOBER_DIR, "LAUNCH-CHECKLIST.md");

// Ensure reports directory exists
if (!existsSync(REPORTS_DIR)) {
  mkdirSync(REPORTS_DIR, { recursive: true });
}

const timestamp = () => new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
const dateStr = () => new Date().toLocaleDateString("en-ZA");
const sastTime = () => new Date().toLocaleString("en-ZA", { timeZone: "Africa/Johannesburg" });

/**
 * Run a vault command and capture output
 */
async function runVaultCommand(cmd: string, arg?: string): Promise<string> {
  try {
    const vaultScript = join(VAULT_DIR, "vault.ts");
    const fullCmd = arg ? `${cmd} "${arg}"` : cmd;
    const result = await $`bun ${vaultScript} ${fullCmd}`.cwd(VAULT_DIR).quiet();
    return result.stdout.toString();
  } catch (error: any) {
    return `Error: ${error.message}`;
  }
}

/**
 * Save a report to Boober agent-reports
 */
function saveReport(type: string, content: string): string {
  const filename = `${type}-${timestamp()}.md`;
  const filepath = join(REPORTS_DIR, filename);
  
  const report = `# ${type.toUpperCase()} Report
**Generated:** ${sastTime()} SAST

---

${content}

---
*Generated by boober-strengthener skill*
`;
  
  writeFileSync(filepath, report);
  return filepath;
}

/**
 * Update INSIGHTS.md with new findings
 */
function updateInsights(insight: string, category: string): void {
  const entry = `\n## [${dateStr()}] ${category}\n\n${insight}\n`;
  
  if (!existsSync(INSIGHTS_FILE)) {
    writeFileSync(INSIGHTS_FILE, `# Boober Strategic Insights\n\nAuto-generated from vault analysis.\n${entry}`);
  } else {
    appendFileSync(INSIGHTS_FILE, entry);
  }
}

/**
 * Extract blockers from context output
 */
function extractBlockers(output: string): string[] {
  const blockers: string[] = [];
  const lines = output.split('\n');
  
  for (const line of lines) {
    if (line.includes('[ ]') && line.length > 5) {
      blockers.push(line.replace(/^-?\s*\[\s*\]\s*/, '').trim());
    }
  }
  
  return blockers;
}

/**
 * Phase 1: Load full context
 */
export async function loadContext(focus: string = "Boober"): Promise<string> {
  console.log(`📊 Loading context with focus: ${focus}`);
  const output = await runVaultCommand("context", `--focus=${focus}`);
  
  // Extract and save blockers
  const blockers = extractBlockers(output);
  if (blockers.length > 0) {
    updateInsights(
      blockers.map(b => `• ${b}`).join('\n'),
      "Extracted Blockers"
    );
  }
  
  saveReport("context", output);
  console.log(`✅ Context loaded. Found ${blockers.length} potential blockers.`);
  return output;
}

/**
 * Phase 2: Trace idea evolution
 */
export async function traceIdea(idea: string, depth: string = "normal"): Promise<string> {
  console.log(`🔍 Tracing idea: ${idea}`);
  const output = await runVaultCommand("trace", `${idea} --depth=${depth}`);
  
  saveReport(`trace-${idea.toLowerCase().replace(/\s+/g, "-")}`, output);
  
  // Extract note count
  const countMatch = output.match(/Found in (\d+) notes/);
  const noteCount = countMatch ? parseInt(countMatch[1]) : 0;
  console.log(`✅ Traced "${idea}" across ${noteCount} notes.`);
  
  return output;
}

/**
 * Phase 3: Connect two domains
 */
export async function connectDomains(domain1: string, domain2: string): Promise<string> {
  console.log(`🔗 Connecting: ${domain1} ↔ ${domain2}`);
  const output = await runVaultCommand("connect", `${domain1} ${domain2}`);
  
  // Extract overlap count
  const overlapMatch = output.match(/Notes mentioning BOTH: (\d+)/);
  const overlap = overlapMatch ? parseInt(overlapMatch[1]) : 0;
  
  // Save insights if meaningful connection
  if (overlap > 0) {
    updateInsights(
      `**${domain1} ↔ ${domain2}** (${overlap} overlapping notes)\n\n${output.slice(0, 500)}...`,
      "Domain Connection"
    );
  }
  
  saveReport(`connect-${domain1}-${domain2}`.toLowerCase().replace(/\s+/g, "-"), output);
  console.log(`✅ Connected domains. ${overlap} notes mention both.`);
  
  return output;
}

/**
 * Phase 4: Generate ideas
 */
export async function generateIdeas(domain: string = ""): Promise<string> {
  console.log(`💡 Generating ideas${domain ? ` for ${domain}` : ""}`);
  const output = domain 
    ? await runVaultCommand("ideas", `--domain=${domain}`)
    : await runVaultCommand("ideas");
  
  saveReport("ideas", output);
  console.log(`✅ Ideas generated.`);
  
  return output;
}

/**
 * Phase 5: Graduate notes to assets
 */
export async function graduateNotes(type: string = "action-plan", topic: string = ""): Promise<string> {
  console.log(`🎓 Graduating notes to ${type}${topic ? `: ${topic}` : ""}`);
  const output = topic 
    ? await runVaultCommand("graduate", `--type=${type} "${topic}"`)
    : await runVaultCommand("graduate", `--type=${type}`);
  
  saveReport("graduate", output);
  console.log(`✅ Notes graduated.`);
  
  return output;
}

/**
 * Full strategic analysis - all phases
 */
export async function fullAnalysis(): Promise<{
  context: string;
  traces: string[];
  connections: string[];
  ideas: string;
  graduates: string;
  reportPath: string;
}> {
  console.log("🚀 Running full Boober strategic analysis...\n");
  
  // Phase 1: Context
  console.log("\n=== PHASE 1: Context Loading ===");
  const context = await loadContext("Boober");
  
  // Phase 2: Trace key ideas
  console.log("\n=== PHASE 2: Idea Tracing ===");
  const keyIdeas = ["taxi safety", "South African market", "driver verification", "marshal"];
  const traces: string[] = [];
  for (const idea of keyIdeas) {
    traces.push(await traceIdea(idea, "deep"));
  }
  
  // Phase 3: Connect domains
  console.log("\n=== PHASE 3: Domain Connections ===");
  const domainPairs = [
    ["Boober", "taxi industry"],
    ["safety", "mobile payments"],
    ["marshals", "community trust"],
    ["driver", "verification"]
  ];
  const connections: string[] = [];
  for (const [d1, d2] of domainPairs) {
    connections.push(await connectDomains(d1, d2));
  }
  
  // Phase 4: Generate ideas
  console.log("\n=== PHASE 4: Idea Generation ===");
  const ideas = await generateIdeas("safety");
  
  // Phase 5: Graduate to action plan
  console.log("\n=== PHASE 5: Note Graduation ===");
  const graduates = await graduateNotes("action-plan", "Boober launch");
  
  // Create summary report
  const summary = `# Boober Strategic Analysis Summary
**Generated:** ${sastTime()} SAST

## Phases Completed
1. ✅ Context Loading
2. ✅ Idea Tracing (${keyIdeas.length} ideas)
3. ✅ Domain Connections (${domainPairs.length} pairs)
4. ✅ Idea Generation
5. ✅ Note Graduation

## Key Findings
See individual reports in \`agent-reports/\` directory.

## Next Actions
1. Review generated insights
2. Update LAUNCH-CHECKLIST.md
3. Address critical blockers
4. Continue agent swarm work
`;
  
  const reportPath = saveReport("full-analysis", summary);
  
  console.log("\n✅ Full analysis complete!");
  console.log(`📄 Report saved: ${reportPath}`);
  
  return { context, traces, connections, ideas, graduates, reportPath };
}

/**
 * Quick context refresh - for pre-run hooks
 */
export async function quickRefresh(): Promise<string> {
  console.log("⚡ Quick context refresh...");
  return await loadContext("Boober");
}

/**
 * Problem solver - find connections for a specific blocker
 */
export async function solveProblem(problem: string): Promise<string[]> {
  console.log(`🔧 Finding solutions for: ${problem}`);
  
  // Trace the problem
  const trace = await traceIdea(problem, "deep");
  
  // Connect to related domains
  const domains = ["taxi", "safety", "mobile", "South Africa", "Boober"];
  const connections: string[] = [];
  
  for (const domain of domains) {
    try {
      const conn = await connectDomains(problem, domain);
      if (conn.includes("Notes mentioning BOTH")) {
        connections.push(conn);
      }
    } catch {}
  }
  
  // Generate ideas
  const ideas = await generateIdeas(problem);
  
  const summary = `# Solution Hunt: "${problem}"

## Traced Evolution
${trace.slice(0, 500)}...

## Domain Connections Found: ${connections.length}

## Generated Ideas
${ideas.slice(0, 500)}...
`;
  
  saveReport(`solve-${problem.toLowerCase().replace(/\s+/g, "-")}`, summary);
  
  return [trace, ...connections, ideas];
}

/**
 * Sync with LAUNCH-CHECKLIST.md
 */
export async function syncChecklist(): Promise<string> {
  console.log("📋 Syncing with LAUNCH-CHECKLIST.md...");
  
  const context = await loadContext("Boober");
  const blockers = extractBlockers(context);
  
  if (!existsSync(LAUNCH_CHECKLIST)) {
    console.log("⚠️ LAUNCH-CHECKLIST.md not found");
    return context;
  }
  
  // Read current checklist
  const checklist = readFileSync(LAUNCH_CHECKLIST, "utf-8");
  
  // Find new blockers not in checklist
  const newBlockers = blockers.filter(b => !checklist.includes(b));
  
  if (newBlockers.length > 0) {
    updateInsights(
      newBlockers.map(b => `• ${b}`).join('\n'),
      "New Blockers Detected"
    );
    console.log(`🆕 ${newBlockers.length} new blockers detected.`);
  }
  
  return context;
}

// CLI interface
const args = process.argv.slice(2);
const command = args[0];

async function main() {
  switch (command) {
    case "full":
      await fullAnalysis();
      break;
    case "context":
      await loadContext(args[1] || "Boober");
      break;
    case "trace":
      await traceIdea(args[1] || "Boober", args[2] || "normal");
      break;
    case "connect":
      await connectDomains(args[1] || "Boober", args[2] || "taxi");
      break;
    case "ideas":
      await generateIdeas(args[1] || "");
      break;
    case "graduate":
      await graduateNotes(args[1] || "action-plan", args[2] || "");
      break;
    case "solve":
      await solveProblem(args[1] || "launch blocker");
      break;
    case "refresh":
      await quickRefresh();
      break;
    case "sync":
      await syncChecklist();
      break;
    default:
      console.log(`
Boober Strengthener - Autonomous Vault Integration

Commands:
  full              Run full strategic analysis (all phases)
  context [focus]   Load context (default: Boober)
  trace <idea>      Trace idea evolution
  connect <a> <b>   Connect two domains
  ideas [domain]    Generate ideas
  graduate [type]   Graduate notes to assets
  solve <problem>   Find solutions for a problem
  refresh           Quick context refresh
  sync              Sync with LAUNCH-CHECKLIST.md

Examples:
  bun strengthener.ts full
  bun strengthener.ts trace "driver safety"
  bun strengthener.ts connect Boober "taxi industry"
  bun strengthener.ts solve "payment integration"
  bun strengthener.ts sync
`);
  }
}

main().catch(console.error);
