#!/usr/bin/env bun
/**
 * Antfarm <-> Agent Lightning Sync
 * Transfers successful patterns from learning to recipes
 */

const LIGHTNING_MEMORY = "/home/workspace/agent-lightning-memory/learnings.jsonl";
const ANTFRAM_RECIPES = "/home/workspace/Skills/antfarm/references/recipes";

interface Learning {
  id: string;
  timestamp: number;
  observation: string;
  action: string;
  reward: number;
  context?: Record<string, unknown>;
}

interface Pattern {
  action: string;
  avgReward: number;
  occurrences: number;
}

async function syncPatterns(): Promise<Pattern[]> {
  try {
    const file = Bun.file(LIGHTNING_MEMORY);
    if (!(await file.exists())) {
      console.log("No learning memory found");
      return [];
    }
    
    const content = await file.text();
    const learnings: Learning[] = content
      .trim()
      .split("\n")
      .filter(Boolean)
      .map(line => JSON.parse(line));
    
    // Group by action and calculate average reward
    const actionMap = new Map<string, { total: number; count: number }>();
    
    for (const learning of learnings) {
      const existing = actionMap.get(learning.action) || { total: 0, count: 0 };
      actionMap.set(learning.action, {
        total: existing.total + learning.reward,
        count: existing.count + 1,
      });
    }
    
    const patterns: Pattern[] = [];
    for (const [action, stats] of actionMap) {
      if (stats.count >= 3) { // Need at least 3 occurrences
        patterns.push({
          action,
          avgReward: stats.total / stats.count,
          occurrences: stats.count,
        });
      }
    }
    
    return patterns.sort((a, b) => b.avgReward - a.avgReward);
  } catch (error) {
    console.error("Error syncing patterns:", error);
    return [];
  }
}

async function createRecipeFromPattern(pattern: Pattern): Promise<void> {
  const recipeName = `learned-${pattern.action.toLowerCase().replace(/\s+/g, "-").slice(0, 30)}`;
  const recipeContent = `# Recipe: ${recipeName}

## Description
Auto-generated from Agent Lightning learning pattern.

## Source
- Pattern: ${pattern.action}
- Average Reward: ${pattern.avgReward.toFixed(2)}
- Occurrences: ${pattern.occurrences}

## Prerequisites
- Determined by pattern context

## Steps
1. Execute: ${pattern.action}
2. Monitor for success indicators
3. Adjust based on feedback

## Files Created
- Generated based on pattern

## Variables
- Context-dependent

---
*This recipe was auto-generated by Agent Lightning → Antfarm sync*
`;

  const recipePath = `${ANTFRAM_RECIPES}/${recipeName}.md`;
  await Bun.write(recipePath, recipeContent);
  console.log(`✓ Created recipe: ${recipeName}`);
}

// CLI
const args = process.argv.slice(2);
const command = args[0];

switch (command) {
  case "patterns": {
    const patterns = await syncPatterns();
    console.log("Top learned patterns:");
    patterns.slice(0, 10).forEach((p, i) => {
      console.log(`${i + 1}. [${p.avgReward.toFixed(2)}] ${p.action} (${p.occurrences}x)`);
    });
    break;
  }
  
  case "create-recipes": {
    const patterns = await syncPatterns();
    const highValue = patterns.filter(p => p.avgReward >= 0.7);
    console.log(`Creating recipes from ${highValue.length} high-value patterns...`);
    for (const pattern of highValue.slice(0, 5)) {
      await createRecipeFromPattern(pattern);
    }
    break;
  }
  
  default:
    console.log("Antfarm ↔ Agent Lightning Sync");
    console.log("Usage:");
    console.log("  patterns       - Show top learned patterns");
    console.log("  create-recipes - Generate recipes from high-value patterns");
}
